### ISSUE TITLE
Help wanted: verify the interpolation of MERSI-2 1000M GEO to 250M GEO

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/python-geotiepoints#47]
National Meteorological Satellite Center's public website has stopped the distrubution of MERSI-2 L1B 250M GEO files for unkown reasons. So I tried to use `GeoInterpolator` to interpolate 1000m lat/lon to 250m. The result image looks good but I still want to have an original 250M to verify my operation. @mraspaud @djhoese If you guys can still have access to 250M GEO files, could you help me to get one? Time node is `20230613_0615`. Thanks!

**Comment by djhoese** [comment]
Here is UW/SSEC's direct broadcast download site:

https://bolt.ssec.wisc.edu/products/fy3/level1/

It has files for 06:45, but not 06:15. Theoretically you should be able to take the 1KM files and compare the interpolated 250m geolocation with the QKM files on this site.

**Comment by yukaribbba** [comment]
I just discovered that using a modified `_modis_interpolator` will generate better result especially at the edge area, and the speed is more than 10x faster than `GeoInterpolator`. Anyway I got satisfying quality, so I'm closing now.
