### ISSUE TITLE
Interpolator returns F-contiguous arrays

### ISSUE THREAD

**Issue by mitkin** [pytroll/python-geotiepoints#5]
The `Interpolator.interpolate` method, specifically scipy's spline interpolator will return arrays that are both F-contiguous and C-contiguous. When viewing/reshaping the array the order gets set to F style, which is causing problems in satpy, since it expects the arrays be in the native, "C" order.

It appears [this line](https://github.com/pytroll/python-geotiepoints/blob/0357eaa73e5f5843154f442ddbb4df693d280097/geotiepoints/interpolator.py#L255) is the trouble maker:
```
            self.new_data[num] = self.new_data[num].reshape(xpoints.shape).T
```
Changing it to:
```
            self.new_data[num] = self.new_data[num].reshape(xpoints.shape).T.copy(order='C')
```
Solves the problem.
The new_data arrays as returned by scipy's spline interpolator, are marked as both, C and F contiguous arrays. 

```
>>> self.new_data[num].flags
Out:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```
It's probably a bug in Scipy, but enforcing the order would be a quick solution.

**Comment by adybbroe** [comment]
Thanks @mitkin Looks good. I have merged it.
