### ISSUE TITLE
When I install this package,it said 'Failed building wheel for python-geotiepoints'.

### ISSUE THREAD

**Issue by bc451270766** [pytroll/python-geotiepoints#8]
Cython will not be used. Use environment variable 'USE_CYTHON=True' to use it
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\geotiepoints
  copying geotiepoints\basic_interpolator.py -> build\lib.win-amd64-3.6\geotiepo
ints
  copying geotiepoints\geointerpolator.py -> build\lib.win-amd64-3.6\geotiepoint
s
  copying geotiepoints\interpolator.py -> build\lib.win-amd64-3.6\geotiepoints
  copying geotiepoints\multilinear.py -> build\lib.win-amd64-3.6\geotiepoints
  copying geotiepoints\version.py -> build\lib.win-amd64-3.6\geotiepoints
  copying geotiepoints\__init__.py -> build\lib.win-amd64-3.6\geotiepoints
  running build_ext
  building 'geotiepoints.multilinear_cython' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C+
+ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for python-geotiepoints

This are the whole errors

When I installed Microsoft Visual C++ 2017，there are the same errors.
I don't know how to install it.

**Comment by bc451270766** [comment]
pip install --upgrade setuptools is no use.
I install this package because it's needed when I install pyspectral.But if I install pyspectral by using python setup.py install , it doesn't give me this error. And I can import pyspectral

**Comment by adybbroe** [comment]
Sorry about that. It was just a try. I am not used to Windows and can't verify here.
I would recommend installing this and other PyTroll packages with conda where possible. Hav you tried that?

`conda install -c conda-forge python-geotiepoints`

Same goes for PyResample for instance...

-Adam

**Comment by bc451270766** [comment]
Thank you very much.
It was installed sucessfully.

**Comment by tapos12** [comment]
`pip install python-geotiepoints ` doesn't work in python 3.6.7

**Comment by djhoese** [comment]
@tapos12 Please file a separate bug report with more information like your operating system, how you installed python, and the exact error message you are getting.
